// Build time, in Node: turns the authored files into the generated ones under `.valance/`.
//
//   content.json    the content model (from content/)
//   program.json    the compiled templates (from src/*.mprx and the built-in views)
//   manifest.json   every tag, prop, scope name and command a template may use, inferred components included (for editors; nothing reads it back)
//   editor.json     where the manifest is and which file is which component (for editors)
//   client.ts       the browser entry: imports the above, the author's `src/main.ts` and every stylesheet under src/
//   server.ts       the server entry: renders a pathname to a document
//
// The two entries are real files, not virtual modules, so an author can read exactly what runs.
import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

import type { Config } from "./config.js";
import { compileViews, SOURCE_DIR } from "./compile.js";
import { readContent } from "./content.js";
import type { DefinedApp } from "./index.js";
import type { Content } from "./model.js";
import { ENTRY_FILE, ensureGeneratedDir, GENERATED_DIR, generated, writeIfChanged } from "./project.js";

const stylesheets = (root: string): ReadonlyArray<string> =>
  existsSync(join(root, SOURCE_DIR)) ? readdirSync(join(root, SOURCE_DIR), { recursive: true, encoding: "utf8" }).filter((file) => file.endsWith(".css")).sort().map((file) => `${SOURCE_DIR}/${file}`) : [];

export const hasEntry = (root: string): boolean => existsSync(join(root, ENTRY_FILE));

const clientSource = (root: string): string => `// Generated by \`valance\`. Do not edit: it is rewritten whenever the project changes.
// @ts-nocheck
import { start } from "@valancex/cli/client";
import content from "./content.json";
import program from "./program.json";
${hasEntry(root) ? `import author from "../${ENTRY_FILE}";\n` : "const author = undefined;\n"}${stylesheets(root).map((file) => `import "../${file}";\n`).join("")}
await start({ content, program, author });
`;

const serverSource = (root: string): string => `// Generated by \`valance\`. Do not edit: it is rewritten whenever the project changes.
// @ts-nocheck
import { createRenderer, pathsOf } from "@valancex/cli/server";
import content from "./content.json";
import program from "./program.json";
${hasEntry(root) ? `import author from "../${ENTRY_FILE}";\n` : "const author = undefined;\n"}
export const render = createRenderer({ content, program, author });
export const paths = () => pathsOf(content);
export { content };
`;

export const writeContent = (root: string, content: Content): boolean => writeIfChanged(generated(root, "content.json"), `${JSON.stringify(content, null, 2)}\n`);

/** The content stage alone: it does not need the author's code. */
export const generateContent = (root: string, config: Config): Content => {
  ensureGeneratedDir(root);

  const content = readContent(root, config);

  writeContent(root, content);

  return content;
};

/** The templates stage: needs the author's definition (the manifest derives from its state and commands). */
export const generateProgram = async (root: string, author: DefinedApp | undefined): Promise<ReadonlyArray<string>> => {
  ensureGeneratedDir(root);

  const compiled = await compileViews(root, author);

  writeIfChanged(generated(root, "program.json"), `${JSON.stringify(compiled.program)}\n`);
  writeIfChanged(generated(root, "manifest.json"), `${JSON.stringify(compiled.manifest, null, 2)}\n`);
  // The one file an editor reads to know the project: where the manifest is, and which file is the template of which component. The conventions stay here, not copied into every editor.
  writeIfChanged(generated(root, "editor.json"), `${JSON.stringify({ version: 1, model: `${GENERATED_DIR}/manifest.json`, components: compiled.files }, null, 2)}\n`);

  return compiled.components;
};

/** The entries; rewritten when `src/main.ts` or a stylesheet is added or removed. */
export const generateEntries = (root: string): boolean => {
  ensureGeneratedDir(root);

  return [writeIfChanged(generated(root, "client.ts"), clientSource(root)), writeIfChanged(generated(root, "server.ts"), serverSource(root))].some(Boolean);
};
