// Where things are in a project. Authored: `valance.json`, `valance.web.json`, `content/`, `public/`, `src/`. Generated and never edited or committed: `.valance/`. The final site: `dist/`.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export const GENERATED_DIR = ".valance";
export const OUTPUT_DIR = "dist";
export const ENTRY_FILE = "src/main.ts";

export const generated = (root: string, name: string): string => join(root, GENERATED_DIR, name);

/** Writes `text` unless the file already says exactly that: a watcher that sees a write should only see a change. Returns whether it wrote. */
export const writeIfChanged = (path: string, text: string): boolean => {
  if (existsSync(path) && readFileSync(path, "utf8") === text) { return false; }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);

  return true;
};

/** Keeps `.valance/` out of version control without asking the author to remember: a `.gitignore` inside it. */
export const ensureGeneratedDir = (root: string): void => {
  writeIfChanged(generated(root, ".gitignore"), "# Generated by `valance`. Never edited, never committed.\n*\n");
};
